\# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=8.4'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=8.4'

script:
- set -o pipefail
- xctool -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test -only XCTest-Gherkin_Tests
- if [ $UI ]; then; xctool -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test -only XCTest-Gherkin_ExampleUITests; fi
- pod lib lint
